version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=test

  web:
    build:
      context: ./repo
    command: 'yarn coverage'
    volumes:
      - ./repo:/server
    ports:
      - "8000:8000"
    depends_on: 
      - db
