version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=admin

  web:
    build:
      context: ./repo
    command: 'pwd && yarn coverage'
    volumes:
      - ./repo:/server
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    depends_on: 
      - db
